name: 'Helm 3'
description: 'Helm 3'
branding:
  icon: 'compass'
  color: 'blue'
inputs:
  exec:
    description: 'The full helm command to run (including helm)'
    required: true
  kubeconfig:
    description: 'The full helm command to run (including helm)'
    required: false
  overrule_existing_kubeconfig:
    description: 'The full helm command to run (including helm)'
    required: false
runs:
  using: 'node16'
  main: 'main.js'
