FROM alpine/helm:3.4.1 AS runtime

# hadolint ignore=DL3002
USER root

# hadolint ignore=DL3018
RUN apk --no-cache --update add git less openssh bash && \
            rm -rf /var/lib/apt/lists/*

RUN mkdir /workdir
COPY entrypoint.sh /workdir/entrypoint.sh
RUN chmod +x /workdir/entrypoint.sh

ENTRYPOINT ["/workdir/entrypoint.sh"]
